resources:
  - name: myGitRepo_hello
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: sangangu/helloworld
      branches:
        include: master
  - name: myBuildInfos
    type: BuildInfo
    configuration:
      sourceArtifactory: My_Own
      buildName: SampleApp
      buildNumber: 1          
pipelines:
  - name: Maven_application
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NAME: Maven_Build
    steps:
      - name: Mvn_Build
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: pom.xml
          inputResources:
            - name: myGitRepo_hello
          integrations:
            - name: My_Own 
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
